### ISSUE TITLE
Change reference to Gatekeeper vs Kyverno article to prod

### ISSUE THREAD

**Issue by chipzoller** [developer-guy/policy-as-code-war#1]
Hi there, @developer-guy . I am the author of the article you cite in your comparison table. It seems that you got a hold of the link from my staging site rather than the "prod" site. That staging link was only for pre-publication, so now that the article is available, I ask that you please reference its prod version at https://neonmirrors.net/post/2021-02/kubernetes-policy-comparison-opa-gatekeeper-vs-kyverno/

Thanks!

**Comment by developer-guy** [comment]
@chipzoller thank you 🙏 btw wonderful blog post, it helped me a lot 🙏🙏

**Comment by chipzoller** [comment]
Thanks and glad to hear it.

**Comment by developer-guy** [comment]
I updated it, thank you so much again 👍  @chipzoller
